name: "💡 Suggestion"
description: "Quick idea or improvement for ActionMenus"
title: "[Suggestion] <short summary>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Quick suggestion for **ActionMenus**? Use this shorter template.
        (For detailed features with JSON examples, use Feature request.)

  - type: textarea
    id: suggestion
    attributes:
      label: Your suggestion
      description: "Keep it short - what should change or be added?"
      placeholder: "Add sound pitch control to sound actions / Make placeholders update faster / etc."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why this idea?
      placeholder: "Makes X easier / Fixes Y annoyance / etc."
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affects
      options:
        - JSON config syntax
        - Actions / commands
        - Placeholders
        - Permissions
        - Performance
        - Other
    validations:
      required: true
